### ISSUE TITLE
Missing source files

### ISSUE THREAD

**Issue by AleksandarDev** [RainbowDashDC/wpGitter#1]
`package.appxmanifest`
`Package.StoreAssociation.xml`

are missing from root folder. Can you please add them? 
They are manifest files used to deploy application to wp (emulator and device).

**Comment by RainbowDashDC** [comment]
Yea, I'm aware. Sadly I HDD wiped before I realized they were needed. I'll see what I can do. Thanks!

**Comment by RainbowDashDC** [comment]
Try removing them from the project and see if it helps.

**Comment by RainbowDashDC** [comment]
Nevermind, that doesn't work. Ugh.

**Comment by RainbowDashDC** [comment]
See latest commit
