### ISSUE TITLE
Decide what CSS framework to use

### ISSUE THREAD

**Issue by AleksandarDev** [RainbowDashDC/wpGitter#4]
I have experience with [{less}](http://lesscss.org/) and [compass](http://compass-style.org/)

**Comment by RainbowDashDC** [comment]
I honestly have no experience with any css framework, I usually just use vanilla, however if you want to convert the current stylesheets to use less and we'd presumably use grunt to compile them down then I'm all for it. It'd be useful to learn less, or etc, anyways.

**Comment by AleksandarDev** [comment]
[Visual Studio Web Essentials](https://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361?SRC=Home) compiles  LESS for you. We can use that.

**Comment by RainbowDashDC** [comment]
Closing because Web Essentials is required for building to begin with, so LESS is fine.
